### ISSUE TITLE
Please publish 1.2.2

### ISSUE THREAD

**Issue by ophilli** [pop-os/sys-mount#17]
Can an owner of https://crates.io/crates/sys-mount please publish v1.2.2 in order to release commits https://github.com/pop-os/sys-mount/commit/e05b6a5c921a19b77cd66a93c9c481ff720b5921 and https://github.com/pop-os/sys-mount/commit/2c7a0ffa468d3493289a280c46e8f220b9ff6dc3 ?

Thank you for merging those PRs so quickly by the way!

**Comment by mmstick** [comment]
Done

**Comment by ophilli** [comment]
Thanks so much @mmstick !
