### ISSUE TITLE
if support mount  --bind ?

### ISSUE THREAD

**Issue by jokemanfire** [pop-os/sys-mount#34]
I didn't find  the interface for bind ,If it not support yet? If it is not supported now, can we increase it？

**Comment by AndrewLipscomb** [comment]
I've come to this repo for this use case as well. 

```
        /// Perform a bind mount, making a file or a directory subtree visible at another
        /// point within a file system. Bind mounts may cross file system boundaries and
        /// span chroot(2) jails. The filesystemtype and data arguments are ignored. Up
        /// until Linux 2.6.26, mountflags was also ignored (the bind mount has the same
        /// mount options as the underlying mount point).
        const BIND = MS_BIND;
```

There is a `BIND` flag option in there - so on the face of it, bind seems to be supported. 

However - I can't seem to actually get it to do a mount - I'm getting some wonderfully helpful errors with code `22`, which means bad options. 

I'm trying the equivalent of 
```
mount --bind /a /b
``` 

with the following 

```
Mount::builder()
                .flags(MountFlags::BIND)
                .mount("/a", "/b");
```

The shell version goes, the Rust one doesn't. 

So unsure if this a bug, me missing something, or something just not being there altogether. I'm going to keep digging to see if that 22 error code is actually turned into something more useful in another context.

**Comment by AndrewLipscomb** [comment]
Ah I'm an idiot - that command I posted above isn't what I actually ran. 

That code above does work @jokemanfire

**Comment by jokemanfire** [comment]
Thank you @AndrewLipscomb, I code follow the Readme
```
 let supported = match SupportedFilesystems::new() {
        Ok(supported) => supported,
        Err(why) => {
            eprintln!("failed to get supported file systems: {}", why);
            exit(1);
        }
    };

    // The source block will be mounted to the target directory, and the fstype is likely
    // one of the supported file systems.
    let result = Mount::builder()
        .fstype(FilesystemType::from(&supported))
        .mount(src, dir);

```
Make me mistakenly think that if both the original and target paths are directories.  This module can detect 'bind' flag auto ... I
 Point out  MountFlags::BIND can run successfully. I means that this module can use 'bind' flag automated ? when the 'src' is dir and 'dst' is directories. Maybe I didn't consider it completely. But pointing out that the operation of  MountFlags is similar to that of the unix::mount module.
